from tkinter import *
root = Tk()
root.title('text')
root.geometry('720x480')
root.minsize(480, 240)
frame1 = Frame(root, borderwidth=1, background='gray')
frame1.grid(row=0, column=0)
label1 = Label(frame1, text='Wellcome')
label1.grid(row=0)
frame2 = Frame(root)
label2 = Label(frame2, text='Enter your name :')
button2 = Button(frame2, text='click')
frame2.grid(row=1, column=0)
label2.grid(row=1, column=0)
button2.grid(row=1, column=1)
frame3 = Frame(root)
label3 = Label(frame3, text='Enter your Roll :')
frame3.grid(row=2, column=0)
label3.grid(row=2, column=0)
button3 = Button(frame3, text='click')
button3.grid(row=2, column=1)
root.mainloop()
